### ISSUE TITLE
아이디/비밀번호 찾기 기능 의문

### ISSUE THREAD

**Issue by wogus1027** [have-a-meal/front_have_a_meal#1]
아이디/비밀번호 찾기 기능에서 어떤 데이터를 받고 인증해서 알려줘야 하는지 모르겠음

현재

아이디 찾기
- 이름(실명)
- 전화번호

<img src="https://github.com/have-a-meal/front_have_a_meal/assets/77985708/6bc1fc81-6998-4ee3-a7a0-767885827d36.png"  width="175" height="400"/>

비밀번호 재설정
- 아이디
- 이름(실명)
- 전화번호

<img src="https://github.com/have-a-meal/front_have_a_meal/assets/77985708/117283e5-9c8e-48e7-a72b-e83301a21e9c.png"  width="175" height="400"/>

유저 인증을  이메일로 바꿀지 의문 -> 학생은 이메일에 아이디가 있어서 대응 가능 하지만 외부인은 아이디가 없어서 대응 불가능
전화번호 인증을 사용 -> 이메일 인증 말고도 전화번호 인증까지 추가해야함(비용 추가) 또한 회원가입 할때도 전화번호 인증을 해야함

**Comment by wogus1027** [comment]
외부인은 전화번호, 패스워드로 로그인하기때문에 아이디 찾기가 필요없고
비밀번호 재설정은 이메일을 받아서 인증

**Comment by jaewoong-gwon** [comment]
#### 학생의 경우
- 학생의 아이디는 학번으로 사용하기 때문에, 학번을 찾는 기능은 저희가 구현해야할 사항이 아니라고 생각되네요!
- 비밀번호 찾기는 이메일 인증이 선행되고, 인증된 경우에 한해 재설정하는 방향으로 얘기가 되어서 이메일을 입력 받는 화면을 구성하면 될 것 같습니다!
#### 외부인의 경우
- 말씀하신 대로 전화번호 인증은  비용 문제가 있어서 선택할 것 같지는 않습니다. 
- 비밀번호 재설정도 학생과 동일하게 구성해주시면 될 것 같습니다!
