### ISSUE TITLE
로그인 화면 UI 질문

### ISSUE THREAD

**Issue by wogus1027** [have-a-meal/front_have_a_meal#2]
<img src="https://github.com/have-a-meal/front_have_a_meal/assets/77985708/e4af55f2-3b05-441a-859a-f1bdc08955c9.png"  width="175" height="400"/>

현재의 화면에서 

학생은 학번, 비밀번호로 로그인하고

외부인은 전화번호, 비밀번호로 로그인하는데 이 UI를 어떻게 구성하는지 의문

**Comment by wogus1027** [comment]
학생은 학번을 입력하는게 이해가 가능하지만 외부인은 불가능 하기 때문에 이를 구분하는 버튼을 추가하여 상태에 따라 ID를 담당하는 텍스트필드의 라벨을 변경하게 만들면 해결이 가능할 것같음

**Comment by jaewoong-gwon** [comment]
![image](https://github.com/have-a-meal/front_have_a_meal/assets/75228991/b4e02fe4-b6ef-409c-8a90-ccbe247e6f07)

롯데시네마 홈페이지에서 캡쳐해왔습니다.
저런 느낌으로 구성하면 좋을것 같습니다~
